# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-22 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BabyTimes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times_type', models.CharField(choices=[('testimonial', 'Testimonial'), ('review', 'Review')], max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BabyTimesTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[(b'en', 'English'), (b'es', 'Spanish'), (b'tr', 'Turkish'), (b'de', 'German'), (b'fr', 'French')], max_length=15, verbose_name='language')),
                ('title', models.CharField(max_length=255)),
                ('timestamp', models.DateField()),
                ('content', models.TextField()),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='pages.BabyTimes', verbose_name='babytimes')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.FileField(blank=True, null=True, upload_to='upload/certification/')),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CertificationTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[(b'en', 'English'), (b'es', 'Spanish'), (b'tr', 'Turkish'), (b'de', 'German'), (b'fr', 'French')], max_length=15, verbose_name='language')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='pages.Certification', verbose_name='certification')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='troubleshootingtranslation',
            name='answer',
            field=models.TextField(),
        ),
    ]
