# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-29 12:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20181128_1801'),
        ('pages', '0003_auto_20181129_1358'),
    ]

    operations = [
    ]
