# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-09 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20190103_1144'),
        ('pages', '0004_auto_20190109_1440'),
    ]

    operations = [
    ]
