# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-16 06:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20190114_1545'),
        ('pages', '0006_auto_20190110_1256'),
    ]

    operations = [
    ]
