# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-16 07:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_merge_20190116_0823'),
        ('pages', '0007_auto_20190116_0916'),
    ]

    operations = [
    ]
