# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-17 09:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_merge_20190116_0957'),
        ('pages', '0008_auto_20190116_1418'),
    ]

    operations = [
    ]
