# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-17 09:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_merge_20190117_1132'),
        ('pages', '0009_auto_20190117_1140'),
    ]

    operations = [
    ]
