# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-21 09:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20190121_1057'),
        ('pages', '0014_auto_20190118_1641'),
    ]

    operations = [
    ]
