# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-21 11:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_auto_20190121_1201'),
        ('pages', '0016_auto_20190121_1239'),
    ]

    operations = [
    ]
