# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-22 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_merge_20190122_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='certifications/'),
        ),
    ]
