# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-23 09:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_auto_20190122_1712'),
        ('pages', '0018_auto_20190123_0843'),
    ]

    operations = [
    ]
