# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-25 08:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_merge_20190121_1323'),
        ('pages', '0020_auto_20190123_1209'),
    ]

    operations = [
    ]
