# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-31 08:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_certification_display'),
        ('pages', '0021_merge_20190125_1024'),
    ]

    operations = [
    ]
