# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-31 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_certification_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='babytimes',
            name='display',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='babytimes',
            name='slug',
            field=models.SlugField(default='slug', max_length=255),
            preserve_default=False,
        ),
    ]
