# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-31 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_auto_20190131_1653'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='babytimes',
            options={'verbose_name': 'Baby Times', 'verbose_name_plural': 'Baby Times'},
        ),
        migrations.AddField(
            model_name='troubleshooting',
            name='slug',
            field=models.SlugField(default='slug', max_length=255),
            preserve_default=False,
        ),
    ]
