# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-31 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_auto_20190131_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticlecomment',
            name='language',
            field=models.CharField(choices=[(b'en', 'English'), (b'es', 'Spanish'), (b'tr', 'Turkish'), (b'de', 'German'), (b'fr', 'French'), (b'ja', 'Japanese')], default='en', max_length=4),
            preserve_default=False,
        ),
    ]
