# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-01 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_troubleshooting_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticlecomment',
            name='language',
            field=models.CharField(choices=[(b'en', 'English'), (b'es', 'Spanish'), (b'tr', 'Turkish'), (b'de', 'German'), (b'fr', 'French'), (b'ja', 'Japanese')], max_length=14),
        ),
        migrations.AlterField(
            model_name='troubleshooting',
            name='display',
            field=models.BooleanField(),
        ),
    ]
