# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-06 09:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_merge_20190131_1037'),
        ('pages', '0026_auto_20190201_1347'),
    ]

    operations = [
    ]
