# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-12 14:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0032_auto_20190207_1313'),
        ('pages', '0032_auto_20190212_1643'),
    ]

    operations = [
    ]
