# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-15 09:31
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0033_merge_20190212_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255)),
                ('display', models.BooleanField()),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CategoryTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[(b'en', b'English'), (b'es', b'Spanish'), (b'tr', b'Turkish'), (b'de', b'German'), (b'fr', b'French'), (b'ja', b'Japanese')], max_length=15, verbose_name='language')),
                ('title', models.CharField(max_length=255)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='pages.Category', verbose_name='Category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='blogarticle',
            name='image',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url=b'/media/', location=b'/Users/paulvonhoesslin/development/connect.snuza.com/webapp/media'), upload_to=pages.models.get_blog_image_path),
        ),
        migrations.AddField(
            model_name='blogarticle',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='pages.Category'),
        ),
    ]
