# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-15 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0034_auto_20190215_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticle',
            name='categories',
            field=models.ManyToManyField(blank=True, to='pages.Category'),
        ),
    ]
