# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-19 04:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0039_auto_20190218_1621'),
        ('pages', '0039_auto_20190215_1424'),
    ]

    operations = [
    ]
