# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-06 11:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0053_auto_20190306_1209'),
        ('pages', '0053_auto_20190305_1729'),
    ]

    operations = [
    ]
