# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-05 13:39
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0055_auto_20190307_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticle',
            name='image',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url=b'/media/', location=b'/Users/paulvonhoesslin/development/connect.snuza.com__master/webapp/media'), upload_to=pages.models.get_blog_image_path),
        ),
    ]
