# Generated by Django 2.1.7 on 2019-04-23 14:29

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0060_auto_20190417_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babytimestranslation',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('tr', 'Turkish'), ('de', 'German'), ('fr', 'French'), ('ja', 'Japanese')], max_length=15, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='blogarticle',
            name='image',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/', location='/Users/paulvonhoesslin/development/connect.snuza.com__master/webapp/media'), upload_to=pages.models.get_blog_image_path),
        ),
        migrations.AlterField(
            model_name='blogarticlecomment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pages.BlogArticle'),
        ),
        migrations.AlterField(
            model_name='blogarticlecomment',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('tr', 'Turkish'), ('de', 'German'), ('fr', 'French'), ('ja', 'Japanese')], max_length=14),
        ),
        migrations.AlterField(
            model_name='blogarticletranslation',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('tr', 'Turkish'), ('de', 'German'), ('fr', 'French'), ('ja', 'Japanese')], max_length=15, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='categorytranslation',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('tr', 'Turkish'), ('de', 'German'), ('fr', 'French'), ('ja', 'Japanese')], max_length=15, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='certificationtranslation',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('tr', 'Turkish'), ('de', 'German'), ('fr', 'French'), ('ja', 'Japanese')], max_length=15, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pagetranslation',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('tr', 'Turkish'), ('de', 'German'), ('fr', 'French'), ('ja', 'Japanese')], max_length=15, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='troubleshootingtranslation',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('tr', 'Turkish'), ('de', 'German'), ('fr', 'French'), ('ja', 'Japanese')], max_length=15, verbose_name='language'),
        ),
    ]
