# Generated by Django 2.1.7 on 2019-05-13 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0062_auto_20190424_1419'),
        ('pages', '0062_auto_20190430_1413'),
    ]

    operations = [
    ]
