# Generated by Django 2.2.1 on 2019-05-21 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0063_auto_20190521_1337'),
        ('pages', '0063_merge_20190513_0850'),
    ]

    operations = [
    ]
